// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBRCNj6ClF_L-lYQfB--ix7hzD2iGUs9g',
    appId: '1:1050467843567:web:718081b60ec44fe305ca1a',
    messagingSenderId: '1050467843567',
    projectId: 'my-seetu-auth',
    authDomain: 'my-seetu-auth.firebaseapp.com',
    storageBucket: 'my-seetu-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1V8W1EOqbOFq3YSBd3oY4eFvGrYXjwvU',
    appId: '1:1050467843567:android:ee672b9b4474ff5f05ca1a',
    messagingSenderId: '1050467843567',
    projectId: 'my-seetu-auth',
    storageBucket: 'my-seetu-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNqVYlgLPS6SqUhlT9XucOy4-jHNL-RSU',
    appId: '1:1050467843567:ios:b5a238310d928ee105ca1a',
    messagingSenderId: '1050467843567',
    projectId: 'my-seetu-auth',
    storageBucket: 'my-seetu-auth.appspot.com',
    iosBundleId: 'com.example.myseettu',
  );
}
